### ISSUE TITLE
MK7 Firmware 2.0.0 unstable Packages button does not work

### ISSUE THREAD

**Issue by SgtFoose** [hak5/mk7-docs#1]
MK7 Firmware 2.0.0 unstable Packages button does not work.

Result from the Chrome Console::
http://172.16.42.1:1471/api/modules/packages/available

DevTools failed to load source map: Could not load content for http://172.16.42.1:1471/assets/thirdparty/xterm.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for http://172.16.42.1:1471/modules/cabinet/cabinet.umd.js.map: HTTP error: status code 401, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by foxtrot** [comment]
Hi,

Thanks for the report. While this isn't the right place for bug reports, I've logged it. This is because we haven't yet turned the feed on for the 2.0.0 beta, it should be live in the next few hours.

Thanks!
